version: '3' #без нее compose не работает (надо смотреть какая версия докера и докер-композ стоит на компе и какой ей допустима version)
services: #сервисы будут располагаться в отдельных контейнерах
    web:
        image: nginx #берем офиц образ с hub.docker.com
        container_name: nginx_blog #псевдоним будущего контейнера
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf #линкуем конфиг сайта с монтируемой фс докер-контейнера
            - #линкуем логи
            - .:/var/www/html #линкуем весь проект, чтобы контейнеру были доступны все папки сайта
        ports:
            - 8080:80
        restart: always # если контейнер с сервером упадет, то автоматом перезапускается
        depends_on:
            - php
            - db
    php:
        build: .docker #взять образ после билда докер-файла DockerFile, лежащего в папке .docker (поставим пхп и расширения)
        container_name: php_blog #псевдоним будущего контейнера
        restart: always # если контейнер с пхп упадет, то автоматом перезапускается
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini #линкуем доп настройки пхп (вывод ошибок)
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini #линкуем конфиги xdebug
            - .:/var/www/html
    composer:
        image: composer #ставим офиц.образ композера
        container_name: composer_blog #псевдоним будущего контейнера
        volumes:
            - .:/app #делаем, чтобы композер видел все папки проекта
        command: install #устанавливаем композер
    db:
        image: mysql
        container_name: mysql_blog #псевдоним будущего контейнера
        restart: always # если контейнер с БД упадет, то автоматом перезапускается
        environment: #настройкиокружения + еще в .env
            - MYSQL_ALLOW_EMPTY_PASSWORD:yes     
        ports:
            - 3307:3306
        volumes:
            - ./.docker/conf/mysql/:/docker-entrypoint-initdb.d/ #линкуем, чтобы БД хранилась в проекта 
